- .github/workflows/rust.yml
- src/lib.rs
This branch adds a rule for GitHub Actions.
Examples:
* Failed:
https://github.com/vbkaisetsu/daachorse/runs/4058781234?check_suite_focus=true
* Succeeded:
https://github.com/vbkaisetsu/daachorse/runs/4058764894?check_suite_focus=true
> Add a rule for GitHub Actions

- README.md
This branch adds a badge to README to show build status.
> Add a badge to show build status

- Cargo.toml
I will release 0.2.1 after this branch is merged.
> Bump up to 0.2.1

- src/builder.rs
- src/lib.rs
I modified `base` and `output_pos` to return optional values. I could not find performance changes with the modification.
> Use options

- src/builder.rs
- src/lib.rs
I refactored some variable names as follows.
- `node` is unified into `state`.
- Array name `pattern_id` is changed into `pattern_ids`.
- Variable `pattern` indicating the id is changed into `pattern_id` (but, the member function name of `Match` is kept).
- The element name of `SparseTrie::nodes` is changed from `node` to `edges` because the element is a vector of pairs (label, child_id) and exactly means the edges rather than a node.
- `out_pos` is unified into `output_pos`.
> Refactoring

- README.md
> Add link to techblog

- Cargo.toml
I chose categories from the following list:
https://crates.io/category_slugs
> Update keywords and categories

- .github/workflows/rust.yml
- src/charwise.rs
- src/charwise/builder.rs
This branch enables `clippy::cast_possible_wrap` in the CI.
> Add clippy::cast_possible_wrap

- Cargo.toml
> Release 0.4.2

- Cargo.toml
> Release 0.4.3

- daacfind/Cargo.toml
- daacfind/src/main.rs
To fix warnings on the CI.
See also https://github.com/clap-rs/clap/issues/3822
> Update clap to 3.2.1

- Cargo.toml
> Add rust-version option to Cargo.toml

- .github/workflows/rust.yml
Checks Minimum Supported Rust Version (MSRV) in the CI.
> Add CI rule for checking MSRV

- src/build_helper.rs
- src/builder.rs
- src/charwise.rs
- src/charwise/builder.rs
- src/lib.rs
- src/tests/double_array_structure.rs
I am not sure if the following part is correct, could you check carefully?
https://github.com/daac-tools/daachorse/blob/4794bcc2d3525dfcb92c93c54ff0a4185c0e7c8e/src/charwise/builder.rs#L324-L327
> Remove INVALID_BASE and use Option<NonZeroU32> for base

- src/charwise/iter.rs
- src/iter.rs
- src/lib.rs
This branch skips some unnecessary conditional branches using `else if`.
> Skip unnecessary conditional branch

- src/bytewise.rs
- src/bytewise/builder.rs
- src/charwise.rs
- src/charwise/builder.rs
This branch
* adds links to some types and structs,
* formats texts,
* modifies descriptions in some Panics sections to clarify what users must specify.
> Format descriptions

- README.md
- src/lib.rs
This branch replaces the Japanese technical details with an English paper uploaded to arXiv.
> Update technical details

- .github/workflows/rust.yml
- Cargo.toml
- README.md
- daacfind/src/main.rs
The command line tool `daacfind` requires Rust 1.61 or higher, so I changed MSRV.
> Refactoring workflow

- .github/workflows/rust.yml
> Remove daacfind from clippy lint

- README.md
- src/bytewise/builder.rs
- src/nfa_builder.rs
> Remove unnecessary mut
