daac-tools/daachorse

bench/Cargo.toml
Thin branch updates yada for the benchmark.
=> Update yada to 0.5.0

src/builder.rs, src/lib.rs
This branch uses `Option::filter()` instead of if-some-else-none.
This also contains some refactoring.
=> Use .filter() instead of if-some-else-none

src/builder.rs, src/lib.rs
I moved constant parameters used only in `builder.rs` to the file. And, `FAIL_INVALID` is replaced into `FAIL_MAX` because a default fail value can be set to zero and the constant parameter will be used only for indicating the maximum possible value.
=> Refactor const params

daacfind/Cargo.toml, daacfind/src/main.rs
This branch replaces structopt with clap.
structopt is a wrapper of clap, but its features are integrated into clap version 3.
=> Replace structopt with clap

src/builder.rs, src/charwise/builder.rs, src/lib.rs
This branch removes the following constants:
* `INIT_CAPACITY`: `states` is initialized by `with_capacity()` with this value, but it is often reallocated for a large automaton. On the other hand, this capacity is too large for small devices.
* `FREE_BLOCKS` and `FREE_STATES`: Some small devices do not have enough memory, so I added an option to change these parameters.
=> Add `n_free_blocks()` option

Cargo.toml, src/charwise.rs, src/lib.rs
This branch adds the following serialization and deserialization functions for convenience.
* `serialize()`
* `serialize_to_vec()`
* `deserialize_unchecked()`
* `deserialize_from_slice_unchecked()`
Deserialization functions do not validate the given automaton, so these are defined as unsafe functions.
It means that the deserialization should only be used when the source of the data is completely trusted.
`serialize()` and `deserialize_unchecked()` use traits under `std::io`, so these functions are unavailable in the `no_std` environment. For bare-metal programming, they must use `serialize_to_vec()` and `deserialize_from_slice_unchecked()` instead.
=> Add serialization and deserialization functions

src/charwise.rs, src/lib.rs
The tail slice is necessary to deserialize other contents next to the automaton together.
=> Return tail of slice from deserialize functions

Cargo.toml
crates.io allows at most 5 keywords, so this branch removes one keyword.
=> Fix keywords

README.md, src/lib.rs
In the previous version, we call non-overlap matching with standard algorithm *shortest matching*.
But, this naming is misleading.
For example, given a text `babc` and patterns `ab|abc|bab`, the option reports `bab`, not shorter `ab`.
This PR fixed the description.
=> Fix document for standard non-overlap matching

src/nfa_builder.rs
Currently, `u32::MAX >> 1` is used as an invalid length.
daachorse does not accept an empty string as a pattern, so it can use 0 as an invalid length.
If daachorse uses a memory efficient output array in the future, the small invalid value will be useful.
=> Use 0 as an invalid length

src/charwise.rs, src/charwise/iter.rs, src/iter.rs, src/lib.rs, src/nfa_builder.rs
This PR improved the data structure for output sets, which stores output sets on a forest representation.
The new forest representation reduces the memory usage on UniDic, as follows.
```
== data/words_100000 ==
daachorse (bytewise): 8700816 bytes, 8.298 MiB
daachorse (charwise): 11210880 bytes, 10.692 MiB
== data/unidic/unidic ==
daachorse (bytewise): 36382056 bytes, 34.697 MiB
daachorse (charwise): 30220136 bytes, 28.820 MiB
== data/words_100000 ==
daachorse (bytewise): 8999820 bytes, 8.583 MiB
daachorse (charwise): 11509884 bytes, 10.977 MiB
== data/unidic/unidic ==
daachorse (bytewise): 29523252 bytes, 28.156 MiB
daachorse (charwise): 23361332 bytes, 22.279 MiB
```
There is no significant difference in matching time.
```
unidic/find_overlapping/daachorse …
```
=> Add forest representation of output sets

bench/benches/benchmark.rs, src/charwise.rs, src/charwise/builder.rs, src/charwise/iter.rs, src/charwise/mapper.rs, src/tests.rs, src/tests/mapper.rs
This PR added code mapping for CharwiseDaachorse.
The code mapping enables to represent most characters with small integers, resulting in faster construction, as follows.
```
unidic/build/daachorse/charwise                                                                          
time:   [1.7010 s 1.7037 s 1.7081 s]
change: [-37.270% -37.017% -36.795%] (p = 0.00 < 0.05)
Performance has improved.
```
There is no significant difference in matching time and memory efficiency.
```
unidic/find_overlapping/daachorse/charwise                                                                            
time:   [6.5671 ms 6.5730 ms 6.5790 ms]
change: [-0.3567% +0.4832% +1.1118%] (p = 0.24 > 0.05)
No change in performance detected.
```
```
== data/unidic/unidic ==
daachorse (charwise): 23361332 …
```
=> Add code mapper in frequency order

src/builder.rs, src/charwise.rs, src/charwise/builder.rs, src/lib.rs, src/nfa_builder.rs
This PR changes the memory layout of `State` to increase the maximum number of states in the automaton.
The current layout is base = 4 bytes, check = 1 bytes, fail = 3 bytes, outpos = 4 bytes.
This new layout is base = 4 bytes, check = 1 bytes, fail = 4 bytes, outpos = 3 bytes.
The memory usage is unchanged.
There is no significant difference in matching time.
```
unidic/find/daachorse   time:   [2.9390 ms 2.9437 ms 2.9491 ms]                                  
change: [-8.5873% -6.9023% -5.5108%] (p = 0.00 < 0.05)
Performance has improved.
Found 1 outliers among 30 measurements (3.33%)
1 (3.33%) high severe
unidic/find_overlapping/daachorse                                                                           
time:   [18.286 ms 18.448 ms 18.624 ms]
change: [-1.0303% +0.1783% …
```
=> Change memory layout of state

src/builder.rs, src/charwise.rs, src/charwise/builder.rs, src/charwise/iter.rs, src/iter.rs, src/lib.rs, src/nfa_builder.rs
This branch uses `Option<NonZeroU32>` for representing `output_pos`.
Currently, the maximum value is used for the invalid value of `output_pos`, but the maximum value of `output_pos` differs between the bytewise DA and the charwise DA.
This change uses `Option<NonZeroU32>` in both DAs to simplify the representation.
=> Use `Option<NonZeroU32>` instead of using `OUTPUT_POS_INVALID`

src/charwise.rs, src/charwise/builder.rs, src/charwise/mapper.rs
This PR modified to use bitwise-xor operations in transition lookups in charwise daachorse, as well as bytewise daachorse.
This modification allows to remove
- casting `u32 <=> i32` because `State::base` is implemented with `u32`, and
- range check in `get_child_index_unchecked`.
The construction time on Unidic was improved by 10%:
```
unidic/build/daachorse/charwise                                                                          
time:   [2.9806 s 2.9934 s 3.0077 s]
change: [-11.141% -10.495% -9.8434%] (p = 0.00 < 0.05)
Performance has improved.
```
There is no significant difference in memory efficiency:
```
== data/unidic/unidic ==
[OLD]
daachorse (charwise): 23413272 bytes, 22.329 MiB
[NEW]
daachorse (charwise): 23465576 bytes, 22.379 MiB
```
=> Use bitwise-XOR instead of PLUS in charwise daachorse

src/nfa_builder.rs
This change removes `LENGTH_INVALID` and uses `NonZeroU32` instead.
=> Use NonZeroU32 in the construction of outputs

src/charwise.rs
This branch improves fail transitions of the charwise daac.
In the charwise daac, `get_next_state_id_unchecked()` can return the root state immediately when the character is not found in the character map.
This change is effective in sparse situations such as words_100000 bench.
```
unidic/find_overlapping/daachorse/charwise
time:   [6.5667 ms 6.5872 ms 6.6170 ms]
change: [-3.1561% -2.6908% -2.1607%] (p = 0.00 < 0.05)
Performance has improved.
Found 2 outliers among 30 measurements (6.67%)
2 (6.67%) high severe
unidic/find_overlapping/daachorse/charwise/no_suffix
time:   [5.7978 ms 5.8123 ms 5.8324 ms]
change: [-3.8307% -3.0936% -2.5559%] (p = 0.00 < 0.05)
Performance has improved.
Found 1 outliers among 30 measurements (3.33%)
1 (3.33%) high severe …
```
=> Move to root state when char is not registered

src/charwise.rs, src/charwise/iter.rs
This change improves fail transitions of the leftmost search in charwise daac.
Currently, the iterator returns the pattern stored in `last_output_pos` when the fail is `DEAD_STATE_ID`.
However, this behavior is inefficient because the automaton has to check the fail transition even if the input character is not registered in the automaton.
This branch changes `get_next_state_id_leftmost_unchecked()` to return `ROOT_STATE_IDX` instead of `DEAD_STATE_IDX` and checks `last_output_pos` if the state is `ROOT_STATE_IDX`.
By this change, `get_next_state_id_leftmost_unchecked()` becomes able to return a value immediately if the character is not registered.
```
unidic/leftmost_longest_find/daachorse/charwise
time:   [5.0194 ms 5.0457 ms 5.0872 ms]
change: [-4.8903% -4.1515% -3.2221%] (p = 0.00 < …
```
=> Share ROOT_STATE_IDX and DEAD_STATE_IDX

src/build_helper.rs, src/builder.rs, src/lib.rs
This PR divided `Extra` from `builder.rs` and generalized the auxiliary data structure in double-array construction.
`BuildHelper` can be used in both the cases of bytewise and charwise, although I will modify `charwise/builder.rs` in another PR.
=> Generalize the auxiliary data structure in double-array construction

src/builder.rs, src/charwise/builder.rs
This PR used `BuildHelper` in Charwise.
Also, I modified `DoubleArrayAhoCorasickBuilder` in Bytewise to create an instance of `BuildHelper` in function `build_double_array` instead of maintaining it as a struct member, because `num_free_blocks` drops an older instance.
=> Use BuildHelper in Charwise

src/build_helper.rs, src/builder.rs, src/charwise/builder.rs, tests/invalid_option_test.rs
If users specify the large number to `num_free_blocks`, the capacity size will be wrapped. This branch checks the value before calculating the capacity size.
Blocked by #52
=> Check overflow in BuildHelper

.github/workflows/rust.yml
This change expects that the crate will be published by the CI when the tag is pushed.
=> Publish crate from CI

.github/workflows/rust.yml, Cargo.toml, README.md, daacfind/src/main.rs, src/bytewise.rs, src/charwise.rs, src/charwise/mapper.rs, src/errors.rs, src/lib.rs
This PR removed IO functions for std::io, fully eliminating std dependencies from daachorse.
This modification disables to save/load the data structure via file streams, although the benefits will be significant:
- Codes are simplified.
- No need to care about invalid file streams.
=> Fully eliminate std dependencies

.github/workflows/rust.yml, bench/src/memory.rs, src/build_helper.rs, src/bytewise.rs, src/bytewise/builder.rs, src/bytewise/iter.rs, src/charwise.rs, src/charwise/builder.rs, src/charwise/iter.rs, src/charwise/mapper.rs, src/lib.rs, src/nfa_builder.rs, src/utils.rs
Since `as` is dangerous due to possible overflow, this branch uses `try_from()` or `from_u32()` for type conversion.
=> Replace as_conversions to try_from()

README.md, bench/benches/benchmark.rs, bench/src/memory.rs, daacfind/src/main.rs, src/bytewise.rs, src/bytewise/builder.rs, src/bytewise/iter.rs, src/charwise.rs, src/charwise/builder.rs, src/charwise/iter.rs, src/lib.rs, src/nfa_builder.rs, src/serializer.rs, tests/aho_corasick_crate_test.rs, tests/invalid_option_test.rs, tests/invalid_pattern_charwise_test.rs, tests/invalid_pattern_test.rs, tests/matchkind_mismatch_charwise_test.rs, tests/matchkind_mismatch_test.rs
This branch uses generics for output values rather than a deterministic type.
When constructing an automaton, this change allows users to specify any type that implements `Copy+Default` as values in `with_values()`. 
Also, when building with `new()`, users can specify any type that implements `Copy+Default+TryFrom<usize>`. If the conversion from `usize` fails, a default value will be assigned.
If the type implements `Serializable`, the automaton can be serialized.
=> Change output type to generic type

src/bytewise.rs, src/bytewise/builder.rs, src/bytewise/iter.rs, src/charwise.rs, src/charwise/builder.rs, src/charwise/iter.rs, src/errors.rs, src/nfa_builder.rs
This branch removes the trait bound `Default` from `V`.
This change allows users to specify more types, including pointer types (raw pointers and references).
I do not observe a significant performance impact with this change.
=> Remove the trait bound Default from V

.github/workflows/rust.yml
This branch enables [sparse-registry](https://blog.rust-lang.org/2022/06/22/sparse-registry-testing.html) on Nightly Cargo.
The build time on Nightly is reduced as follows:
https://github.com/daac-tools/daachorse/actions/runs/2660385065
=> Enable sparse-registry on nightly Cargo

src/build_helper.rs, src/bytewise.rs, src/bytewise/iter.rs, src/charwise.rs, src/charwise/iter.rs, src/nfa_builder.rs
This branch renames some functions as follows:
* Removes the prefix `get_`.
* Removes the prefix `set_` from zero-cost functions, adds the suffix `_mut`, and changes to return the mutable reference.
For some structures, leave `set_` for consistency.
=> Rename some functions following API guidelines

src/charwise/iter.rs, src/intpack.rs
Fixes clippy errors on nightly: https://github.com/daac-tools/daachorse/actions/runs/12531326212/job/34948819233
=> Parenthesize shift expressions
